name: Build & Push keydb/pterodactyl/latest to Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "keydb/pterodactyl/latest**"
  pull_request:
    branches:
      - main
    paths:
      - "keydb/pterodactyl/latest**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      root_directory: keydb/pterodactyl
      work_directory: keydb/pterodactyl/latest
      image_name: rust