name: Build & Push node/pterodactyl/18/debian to Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "node/pterodactyl/18/debian/**"
  pull_request:
    branches:
      - main
    paths:
      - "node/pterodactyl/18/debian/**"
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      root_directory: node/pterodactyl
      work_directory: node/pterodactyl/18/debian
      image_name: node