name: Build & Push rust/1.61.0/alpine to Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "rust/1.61.0/alpine/**"
  pull_request:
    branches:
      - main
    paths:
      - "rust/1.61.0/alpine/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@v2.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@v3.2.0

      - name: Set WORKDIR
        run: echo "WORKDIR=rust/1.61.0/alpine" >> $GITHUB_ENV

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`npm exec -sy @hazmi35/extract-docker-baseimg-recipe $WORKDIR/Dockerfile tags`
          PLATFORMS=`npm exec -sy @hazmi35/extract-docker-baseimg-recipe $WORKDIR/Dockerfile platforms`
          VARIANT=`npm exec -sy @hazmi35/extract-docker-baseimg-recipe $WORKDIR/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          echo "::set-output name=tags::${TAGS//$', '/'%0A'}"
          echo "::set-output name=platforms::${PLATFORMS//$', '/'%0A'}"
          echo "::set-output name=variant::$VARIANT"
      - name: Generate Docker image metadata
        uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: |
            ghcr.io/zhycorp/rust
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@v3.0.0
        with:
          context: ${{ env.WORKDIR }}
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}